server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: eureka_client_route
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/?(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
